### ISSUE TITLE
转换出错

### ISSUE THREAD

**Issue by sanxianlee** [foxitdog/wx2ali#9]
Parse Error: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "base" at 0, attempted to resolve relative to "/Users/levent/coding/AntProjects/MegoTest"
    at /usr/local/lib/node_modules/wx2ali/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/wx2ali/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/wx2ali/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/wx2ali/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/wx2ali/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/wx2ali/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/wx2ali/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Object.module.exports.replace (/usr/local/lib/node_modules/wx2ali/lib/JSApiPropReplace.js:10:19)
    at wx2ant (/usr/local/lib/node_modules/wx2ali/index.js:370:27)

**Comment by Star-Sea** [comment]
同问

**Comment by foxitdog** [comment]
这个有当时的截图吗？还有可以吧文件中的内容麻烦发下，以便于寻找问题

**Comment by foxitdog** [comment]
出现转换错误是可以试下  
1、npm uninstall wx2ali -g
2、npm i wx2ali -g
之后重新转换下试试

**Comment by hetengji** [comment]
同问

**Comment by foxitdog** [comment]
> 同问

你按照
https://github.com/foxitdog/wx2ali/issues/9#issuecomment-450119106 这个试试看，如果还有的话麻烦截图，或者把文件内容发下，我这边来查找问题。

**Comment by hetengji** [comment]
![1546580494 1](https://user-images.githubusercontent.com/30951653/50675046-76d54200-1026-11e9-9669-9df0fe5b2f0b.jpg)

**Comment by foxitdog** [comment]
你看看你的安装目录下有没有‘babel-plugin-transform-object-rest-spread‘这个模块
![image](https://user-images.githubusercontent.com/19977685/50675201-725d5900-1027-11e9-8d99-3dfc3a6a38e8.png)
![image](https://user-images.githubusercontent.com/19977685/50675233-b2bcd700-1027-11e9-8db0-5eabdd6dfb7f.png)

**Comment by hetengji** [comment]
老铁 有的
![1546581567 1](https://user-images.githubusercontent.com/30951653/50675412-0c71d100-1029-11e9-80a1-5fd6d09287b4.jpg)
![1546581590 1](https://user-images.githubusercontent.com/30951653/50675414-0c71d100-1029-11e9-8aa6-b5235c34d910.jpg)

**Comment by foxitdog** [comment]
加个好友吧
qq:895423140,细聊

**Comment by foxitdog** [comment]
该问题是因为无法正确的定位到 babel-plugin-transform-object-rest-spread 模块导致的问题，可以通过该命令安装上模块 `npm i babel-plugin-transform-object-rest-spread@^6.26.0 -g` 然后重新开始，记的重新copy份文件，以防止被多次处理。

**Comment by foxitdog** [comment]
问题复现，已经解决，请升级到1.1.7 。
